name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.11.4'

    - name: Install ghr
      run: |
        echo $PATH
        echo $GOROOT
        echo $GOPATH

        #export PATH=$PATH:$HOME/go/bin:$HOME/workspace/bin
        export GOPATH=$HOME/go
        
        echo `which go`
        mkdir -p "$GOPATH"

        go get github.com/tcnksm/ghr

    - name: Publish assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_REPONAME: ${{ github.repository }}
      run: |
        #export PATH=$PATH:$HOME/go/bin:$HOME/workspace/bin
        export GOPATH=$HOME/go

        ghr
